title: Blog | H_Xian
subtitle: Backend Engineer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://n960321.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/about" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /
    - text: Blog
      url: /blog
    # - text: Shop
    #   url : /shop
    # - text: Contact Me
    #   url : /contact
    # - text: Styleguide
    #   url: /styleguide


# Edit these details

author_logo: profile.png
author: H_Xian
author_bio: 嗨，我是黃賢。出生於1994，對任何事物都充滿好奇，且不輕言放棄。這個網站用來介紹我自己 和 記錄我在程式語言相關的部落格。
author_email: "n960321@gmail.com"
author_location: Taichung , Taiwan
# author_website_url: "http://johndoe.com"

author_work_experiences:
            - company_name: 光晨科技有限公司
              company_logo: kc.png
              # company_url: https://google.com
              designation: Backend Engineer
              description: 開發及維護遊戲伺服器專案
              visibility: true
            - company_name: 恩連科技有限公司
              company_logo: netbwm.png
              company_url: http://www.netbwm.com
              designation: Developer
              description: 串接POS系統行動支付功能、開發優惠券系統、開發LINE Bot
              visibility: true

author_education_details:
              - college_logo: ncut.jpg
                college_name: 國立勤益科技大學
                college_url: http://web2.ncut.edu.tw/
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: true

# social links
# twitter_username: 
github_username:  n960321
# facebook_username: johndoe
linkedin_username: n960321
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
telegram_username: h_xian
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments using disqus 
# disqus_shortname: n960321

# wakatime username (coding activity)
wakatime_username: n960321

# formspree (contact form)
formspree_email: n960321@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

theme: jekyll-theme-cayman

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - config.ru
